// product_const_action.js
export const GET_PRODUCTS_SUCCESS = "productReducer/GETPRODUCTSSUCCESS";
export const GET_PRODUCTS_FAILURE = "productReducer/GETPRODUCTSFAILURE";

export const GET_PRODUCTS_BY_CATEGORY_SUCCESS =
  "productReducer/GETPRODUCTSBYCATEGORIESUCCESS";
export const GET_PRODUCTS_BY_CATEGORY_FAILURE =
  "productReducer/GETPRODUCTSBYCATEGORYFAILURE";

export const SEARCH_PRODUCT_SUCCESS = "productReducer/SEARCHPRODUCTSUCCESS";
export const SEARCH_PRODUCT_FAILURE = "productReducer/SEARCHPRODUCTFAILURE";
export const GET_ORDERS_REQUEST = "orderReducer/GET_ORDERS_REQUEST";
export const GET_ORDERS_SUCCESS = "orderReducer/GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAILURE = "orderReducer/GET_ORDERS_FAILURE";

export const ADD_ORDER_REQUEST = "orderReducer/ADD_ORDER_REQUEST";
export const ADD_ORDER_SUCCESS = "orderReducer/ADD_ORDER_SUCCESS";
export const ADD_ORDER_FAILURE = "orderReducer/ADD_ORDER_FAILURE";

// FOR MERCHANTS
export const GET_REGISTERED_PRODUCTS_REQUEST =
  "GET_REGISTERED_PRODUCTS_REQUEST";
export const GET_REGISTERED_PRODUCTS_SUCCESS =
  "GET_REGISTERED_PRODUCTS_SUCCESS";
export const GET_REGISTERED_PRODUCTS_FAILURE =
  "GET_REGISTERED_PRODUCTS_FAILURE";

export const ADD_PRODUCTS_REQUEST = "ADD_PRODUCTS_REQUEST";
export const ADD_PRODUCTS_SUCCESS = "ADD_PRODUCTS_SUCCESS";
export const ADD_PRODUCTS_FAILURE = "ADD_PRODUCTS_FAILURE";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";

export const ADD_REGISTERED_PRODUCT_REQUEST = "ADD_REGISTERED_PRODUCT_REQUEST";
export const ADD_REGISTERED_PRODUCT_SUCCESS = "ADD_REGISTERED_PRODUCT_SUCCESS";
export const ADD_REGISTERED_PRODUCT_FAILURE = "ADD_REGISTERED_PRODUCT_FAILURE";
